---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install NodeJs and NPM"
  apt:
    name: "nodejs"
    state: latest
    update_cache: yes
  
- name: "Install pm2"
  apt:
    name: "pm2"
    state: latest
    update_cache: yes

- name: "Create web directory"
  file:
    path: ~/web
    state: directory
    mode: 0755

- name: "Copy Index file to web directory"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "Start pm2"
  shell: pm2 start ~/web/index.html --name -f
