---
- name: "update yum packages."
  become: true
  yum:
    update_cache: true

- name: "upgrade packages"
  become: true
  yum:
    name: "*"
    state: latest

- name: "Install NodeJs and NPM"
  yum:
    name: "nodejs"
    state: latest
    update_cache: yes
  
- name: "Install pm2"
  npm:
    name: "pm2"
    global: yes
    state: latest
    production: yes

- name: "Create web directory"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: 0755

- name: "Copy Index file to web directory"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "Start pm2"
  shell: pm2 start ~/web/index.html --name -f
